version: "3.9"

services:

  ms-auth:
    build: ./backend/ms-auth
    ports:
      - "4000:4000"
    env_file:
      - ./backend/ms-auth/.env
    command: npm run dev

  ms-predios:
    build: ./backend/ms-predios
    ports:
      - "4001:4001"
    env_file:
      - ./backend/ms-predios/.env
    command: npm run dev

  ms-cultivo:
    build: ./backend/ms-cultivo
    ports:
      - "4002:4002"
    env_file:
      - ./backend/ms-cultivo/.env
    command: npm run dev

  ms-inspecciones:
    build: ./backend/ms-inspecciones
    ports:
      - "4003:4003"
    env_file:
      - ./backend/ms-inspecciones/.env
    command: npm run dev

  ms-auditoria:
    build: ./backend/ms-auditoria
    ports:
      - "4004:4004"
    env_file:
      - ./backend/ms-auditoria/.env
    command: npm run dev

  api-gateway:
    build: ./backend/api-gateway
    ports:
      - "5000:5000"
    env_file:
      - ./backend/api-gateway/.env
    command: npm run dev
    depends_on:
      - ms-auth
      - ms-predios
      - ms-cultivo
      - ms-inspecciones
      - ms-auditoria

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local
    command: npm run dev
